# Generated by Django 3.1.4 on 2020-12-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('general_information_about_the_resource', models.TextField()),
                ('adres_img_for_general_information_about_the_resource', models.TextField()),
                ('date_of_resourc_creation', models.TextField()),
                ('name_administrator', models.TextField()),
                ('other', models.TextField()),
                ('resource_content_date', models.TextField()),
                ('publications_per_day', models.TextField()),
                ('the_main_focus_of_the_channel', models.TextField()),
                ('related_areas', models.TextField()),
                ('channel_content', models.TextField()),
                ('adres_img_for_views', models.TextField()),
            ],
        ),
    ]
