# Generated by Django 3.1.4 on 2020-12-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramChannels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='adres_img_for_general_information_about_the_resource',
            field=models.FileField(upload_to='TelegramChannels/Channels'),
        ),
    ]
