# Generated by Django 3.1.4 on 2020-12-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramChannels', '0003_auto_20201207_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channels',
            old_name='adres_img_for_views',
            new_name='views',
        ),
    ]
